site_name: Guide Pratiche

site_url: https://aleprevitera.github.io/guide/

repo: aleprevitera/guide

theme:
  name: material
  # custom_dir: overrides
  language: it
  palette: 
    # Modo Chiaro (Default)
    - scheme: default
      primary: teal # Colore "Medico"
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Passa alla modalità scura
    # Modo Scuro (Per chi studia di notte)
    - scheme: slate
      primary: teal
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Passa alla modalità chiara
  features:
    - navigation.tabs # Menu a schede in alto
    - navigation.top  # Tasto "Torna su"
    - navigation.sections # Raggruppa le sezioni nel menu laterale
    - navigation.indexes # index.md diventa pagina della sezione
    - content.code.copy # Tasto copia per i codici
    - navigation.footer
  font:
    text: Noto Sans

markdown_extensions:
  - admonition # I box colorati
  - pymdownx.details # Per creare sezioni "spoiler" che si aprono/chiudono
  - pymdownx.superfences
  - md_in_html # Per inserire codice HTML
  - pymdownx.tabbed: # Per creare tab dentro le pagine
      alternate_style: true 
  - attr_list # Per aggiungere classi CSS se serve
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

hooks:
  - hooks.py


plugins:
  - search
  - awesome-pages
  - macros
  - table-reader

copyright: "AGP x FR"

extra:
  generator: false

extra_css:
  - https://fonts.googleapis.com/css2?family=Material+Icons
  - stylesheet/extra.css